title: "GARCIA LMI&kJ"
email: "contacto@garcialmikj.com"
description: "Servicios Profesionales de Mantenimiento de Jardines e Infraestructura. Ecatepec, Tecámac y alrededores."
baseurl: ""
url: "https://garcialmikj.com"

markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - original.html
  - scratch/
  - extract.js
