title: "GARCIA LMI&kJ"
email: "contacto@garcialmikj.com"
description: "Servicios Profesionales de Mantenimiento de Jardines e Infraestructura. Ecatepec, Tecámac y alrededores."
baseurl: "/jardineria-web" # the subpath of your site, e.g. /blog
url: "" 

markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - original.html
  - scratch/
  - extract.js
